[package]
name = "hello_rust"
version = "0.1.0"
edition = "2021"
authors = ["Deren Vural derenv@live.co.uk"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
